name: Build doc and update gh pages
on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  build-test-doc:
    name: build test doc
    runs-on: ubuntu-latest

    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          repository: michaelchin/plate-model-manager
          token: ${{ secrets.GH_PAGE_COMMIT_TOKEN }}
          path: main

      - name: Checkout github pages branch
        uses: actions/checkout@v4
        with:
          repository: michaelchin/plate-model-manager
          ref: gh-pages
          token: ${{ secrets.GH_PAGE_COMMIT_TOKEN }}
          path: gh-pages

      - name: Build doc
        run: |
          chmod +x ./main/scripts/build-workflow.sh
          cd main
          ./scripts/build-workflow.sh
          cd ..
        env:
          GITHUB_TOKEN: "${{secrets.GH_PAGE_COMMIT_TOKEN}}"

      - name: Update github pages
        run: |
          chmod +x ./main/scripts/update-gh-pages.sh
          ./main/scripts/update-gh-pages.sh
        env:
          GITHUB_TOKEN: "${{secrets.GH_PAGE_COMMIT_TOKEN}}"
