name: Create a new release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Release.txt
          draft: false
          generate_release_notes: true
      - name: PyPI Publish
        run: |
          chmod +x ./scripts/pypi-publish.sh
          ./scripts/pypi-publish.sh '${{secrets.PYPI_UPLOAD}}'
