name: Unittest Windows

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
  workflow_dispatch:
    inputs:
      pmm_test_level:
        description: PMM_TEST_LEVEL to use when running unittest
        required: false
        default: "0"
        type: choice
        options:
          - "0"
          - "1"
          - "2"

jobs:
  unittest:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    defaults:
      run:
        shell: bash -el {0}

    if: !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v4
      - name: Install PMM and dependencies
        run: |
          python3 -m pip install requests
          python3 -m pip install requests
          python3 -m pip install aiohttp
          python3 -m pip install nest_asyncio
          python3 -m pip install joblib
          pip3 install .

      - name: Run tests
        env:
          PMM_TEST_LEVEL: ${{ github.event.inputs.pmm_test_level || '1' }}
        run: |
          cd ./unittest
          python3 -m unittest -vv --buffer
